version: "3" 
services:
  server: # サービス名 
    container_name: bus_monitor # コンテナ名
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: Asia/Tokyo
    volumes:
      - ./:/tmp/work/ #現在のフォルダをコンテナにマウント  (ローカルのディレクトリ):(コンテナ内のディレクトリ)
    tty: true  #コンテナが起動し続ける